### ISSUE TITLE
Help with graphql?

### ISSUE THREAD

**Issue by rjpalermo1** [sibelius/koa-passport-mongoose-graphql#10]
Hello, I am starting my journey to graphql and keep coming back to your stack here as the most complete  with modules I am looking for.  I can get it launched but am having a hard time finding how to get into the http://localhost:4000/graphql - everything is returning a 404.

Got a sec to help me?

**Comment by sibelius** [comment]
The GraphQL is in /api/graphql, sorry about that I will open an issue to fix this

**Comment by rjpalermo1** [comment]
Perfect, thank you!
