### ISSUE TITLE
Use Standard Style

### ISSUE THREAD

**Issue by lucasbento** [sibelius/koa-passport-mongoose-graphql#14]
Use [standard](https://github.com/feross/standard) to enforce consistent style and catch errors.

**Comment by sibelius** [comment]
we could start with this .eslintrc (https://gist.github.com/cletusw/e01a85e399ab563b1236), or follow airbnb style

**Comment by lucasbento** [comment]
@sibelius https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/README.md this one?

Looks good, but standard appears to be much easier to config and use.
